#Sample docker-compose.yaml deploying Pi-hole and Unbound 
#with a Bridged Network.
#This example needs to be modified to reflect your network environment,
#especially the values in angle brackets (<>) must be adapted to your needs.
#This file is the one I'm using and was slightly modified with added IPv6
#support (which I'm not using currently).

version: '2'

services:
  pihole:
    container_name: pi-hole
    image: pihole/pihole:latest
    hostname: pi-hole
    domainname: <yourdomain.lan>
    depends_on:
      - unbound
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    networks:
      dns_net:
        ipv4_address: 172.20.0.6
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=$WEBPASSWORD
      - PIHOLE_DNS_=172.20.0.7#5335
      - CUSTOM_CACHE_SIZE=0
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
     
unbound:
    container_name: unbound
    image: madnuttah/unbound:latest
    hostname: unbound
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    networks:
      dns-net:
        ipv4_address: 172.20.0.7 #e.g. 172.20.0.253
        #ipv6_address: <UNBOUND_IPv6_ADDRESS> #e.g. fd11:aa:1234:1234::505
    environment: 
      TZ: "Europe/Madrid" #e.g. "America/New_York"
      ServerIP: 172.20.0.7 #e.g. 172.20.0.253 or fd11:aa:1234:1234::505
      #VIRTUAL_HOST: <unbound.yourdomain.lan>
    volumes:       
      - ./unbound/unbound.conf:/usr/local/unbound/unbound.conf:rw #Your local path to Unbound
      - ./unbound/conf.d/:/usr/local/unbound/conf.d/:rw
      - ./unbound/iana.d/:/usr/local/unbound/iana.d/:rw
      - ./unbound/log.d/unbound.log:/usr/local/unbound/log.d/unbound.log:rw
      - ./unbound/zones.d/:/usr/local/unbound/zones.d/:rw
    restart: unless-stopped
    healthcheck:
      test: /usr/local/sbin/healthcheck.sh
      interval: 60s
      retries: 5
      start_period: 15s
      timeout: 30s
    
networks:
  dns_net:
    driver: bridge
    ipam:
        config:
        - subnet: 172.20.0.0/16
